### ISSUE TITLE
Examples still use newEnvironmentComponent, but that seems to have been removed

### ISSUE THREAD

**Issue by Goldenlion5648** [abisxir/alasgar#3]
I am trying to run the hello.nim file, and I get the error 
```
hello.nim(10, 11) Error: undeclared identifier: 'newEnvironmentComponent'
```

It looks like this used to exist in the components folder, but was removed

**Comment by marioboi3112** [comment]
i am also getting the same issue when trying to run examples made with alasgar....

**Comment by abisxir** [comment]
I removed invalid examples and just "hello.nim" remains. Will add working examples in a structured way.
