### ISSUE TITLE
[BUG] Can't run the example

### ISSUE THREAD

**Issue by milen-prg** [abisxir/alasgar#4]
I do exactly as in your description, but at try to run the hello.exe:

❯ hello.exe
could not load: SDL2_mixer.dll

Windows 10 Pro 64 bit, all updated.

**Comment by abisxir** [comment]
As you see in the error, the executable file cannot find SDL2 dlls. It is not related to alasgar, it is related to the SDL2 installation. Have you installed them?

**Comment by milen-prg** [comment]
@abisxir I thing on Windows these dlls must be embedded in the game engine. I have downloaded these SDL dlls and paste at the example exe folder, but it continue to show this error.

On the other Windows PC, it gives:

main.exe
* SDL initialized.
* SDL window created!
Device and render info:
  SDL linked version  : 2.30.3
  Version: 4.6.0 NVIDIA 560.81
  Vendor: NVIDIA Corporation
  Renderer: NVIDIA GeForce RTX 3060/PCIe/SSE2
  Max varying vectors: 31
* Framebuffer initialized!
source=0x8246 type=0x8251 id=0x20071 severity=0x826b: Buffer detailed info: Buffer object 1 (bound to GL_ARRAY_BUFFER_ARB, usage hint is GL_STATIC_DRAW) will use VIDEO memory as the source for buffer object operations.
* Skybox initialized!
* Shadow initialized!
* Graphics initialized!

And the windows instantly closes itself.

**Comment by abisxir** [comment]
It can cause other issues if I bundle it with the engine as may the developers use other parts of SDL2 (different version) with the engine so better keep it as external dependency, but for the latest issue, could you please paste the source code here?

**Comment by abisxir** [comment]
Please pull the latest version and reinstall it, be sure that you remove the previous installations of alasgar. (in nimble pkgs)
To use sdl2 with nim in windows please read here: [SDL2 for nim](https://github.com/nim-lang/sdl2?tab=readme-ov-file#windows)
The same should happen to SDL2_mixer, you need to download minigw version of it and put it beside bin folder of minigw: [SDL2_mixer](https://github.com/libsdl-org/SDL_mixer/releases/download/release-2.8.0/SDL2_mixer-devel-2.8.0-mingw.zip)
As windows is not my main development PC, I do not face such issues and each time a bug is reported I should get back to my windows PC and warm it up again :)

**Comment by milen-prg** [comment]
I copied the new Windows 64 bit SDL2 dells at the main.exe and it works. Thank you!
