### ISSUE TITLE
Proper Way to Run External Code

### ISSUE THREAD

**Issue by jmwright** [abisxir/alasgar#5]
Sorry to post a general question here, but I don't see anywhere else to do so.

I have a file watcher that will send the contents of a file to a server whenever there is a change, and gets mesh data back. I want to display that mesh data using alasgar. I am trying to determine the proper way to integrate this with the loop of the game engine. Godot has the `_process` function that can be used for some things, although this server-side interaction is too slow to be in that function (or at least it would be bad design).

How should I go about making this work with alasgar?

**Comment by abisxir** [comment]
You can do it in alasgar also, what you need is just a function and a component if you need to keep state:

```nim
type
    # You keep any state you like here
    MyComponent = ref object of Component

# I consider that you setup everything, like scene, camera etc:
let myEntity = newEntity(scene, "My entity")

proc process(script: ScriptComponent) =
    # Get my component instance
    let mc = script[MyComponent]
    # You write your code here
    #var meshData = getItFromSomewhere(mc)
    # Decide how to render your mesh, you can set it on a entity
    # you can create a new entity and remove the old one as you like

# Here I set the script to run in engine main loop before rendering each frame
program(myEntity, process)
# If you need to keep an state and you defined a state component, just add it.
add(myEntity, MyComponent())

# Add my entity to the scene to make it alive
add(scene, myEntity)

# Renders the scene
render(scene)
# Runs game main loop
loop()
```

**Comment by abisxir** [comment]
Your problem actually is just how you get the data without blocking the main loop, that is actually not alasgar's issue, it is a general issue when you want to load something from a blocking device, like disk or network. 
What i suggest is to have anoher thread running and preparing data and communicating with this process function using a channel. In this way, here you just check the channel and if there is a data available you render it. I have done it this way for a 3d chess application. You can write to me in nim game developing channel in discord, if you need extra help.

**Comment by jmwright** [comment]
Thank you @abisxir !
